evaluate: True

pretrain:
    path: model_zoo/AVA-Kinetics_SLOWFAST_R101_ACAR_HR2O_DEPTH1.pth.tar
    delete_prefix: module.head.module.fc2.weight

result_path: experiments/AVA-Kinetics/trainAVA_SLOWFAST_R101_ACAR_HR2O_DEPTH1
manual_seed: 1
print_freq: 20

model:
    freeze_bn: True
    backbone:
        arch: slowfast101
        learnable: True
        kwargs:
            alpha: 4
            beta: 0.125
    neck:
        type: basic
        kwargs:
            bbox_jitter:
                num: 1
                scale: 0.075
            num_classes: 3
            multi_class: False
    head:
        type: acar
        kwargs:
            width: 2304
            roi_spatial: 7
            num_classes: 3
            depth: 1
            mlp_1x1: True

loss:
    type: pose_criterion

train:
    root_path: data/videos
    annotation_path: annotations/train.pkl
    batch_size: 1

    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: RandomHorizontalFlip
          - type: ToTensor
            kwargs:
                norm_value: 1.
          - type: Normalize
            kwargs:
                mean: [ 110.63666788, 103.16065604, 96.29023126 ]
                std: [ 38.7568578, 37.88248729, 40.02898126 ]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    n_epochs: 16
    val_freq: 1
    save_freq: 1

    optimizer:
        type: SGD
        kwargs:
            momentum: 0.9
            weight_decay: 0.0000001
            nesterov: True

    scheduler:
        type: step
        milestone_epochs: [5.6, 5.8]
        lr_mults: [0.1, 0.1]
        base_lr: 0.008
        warmup_lr: 0.064
        warmup_epochs: 1

val:
    root_path: data/videos
    annotation_path: annotations/val.pkl
    batch_size: 1

    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: ToTensor
            kwargs:
                norm_value: 1.
          - type: Normalize
            kwargs:
                mean: [110.63666788, 103.16065604, 96.29023126]
                std: [38.7568578, 37.88248729, 40.02898126]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    with_label: True
    eval_mAP:
        labelmap: annotations/action_list.pbtxt
        groundtruth: annotations/groundtruth.csv
